# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
#before_script:
#  - docker info

#build_image:
#  script:
#    - docker build --rm=true -t clara .
#    - docker run -ti -h clara --name clara clara /bin/bash

image: python:3.6

#pages:
#  script:
#  - pip install --no-cache-dir -r requirements.txt
#  - FLASK_APP=app.py flask run
#  artifacts:
#    paths:
#    - public
#  only:
#  - master


pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - apt-get update -q -y
    - apt-get install -y python-pip
    - pip install --no-cache-dir -r requirements.txt
    - FLASK_APP=flaskapp.py flask run
  artifacts:
    paths:
      - public
  only:
    - master
